# Generated by Django 2.2.5 on 2019-09-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('enderecos', '0001_initial'),
        ('core', '0006_auto_20190913_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(blank=True, null=True, to='atracoes.Atracao'),
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='avaliacoes',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.Comentario'),
        ),
    ]
