# Generated by Django 2.2.5 on 2019-09-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='aprovado',
        ),
    ]
